function [fitresult, gof] = createFitCsTp(EpVec, CsTp, errCsTp)
%CREATEFIT(EPVEC,CSTP,ERRCSTP)
%  Create a fit.
%
%  Data for 'fitCsTp' fit:
%      X Input : EpVec
%      Y Output: CsTp
%      Weights : errCsTp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-May-2017 12:46:42


%% Fit: 'fitCsTp'.
[xData, yData, weights] = prepareCurveData( EpVec, CsTp, errCsTp );

% Set up fittype and options.
ft = fittype( 'sqrt(2/pi)*a/w *exp(-((x-x0)/w)^2)+b*x+c+d/x', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.StartPoint = [0.655098003973841 0.162611735194631 0.118997681558377 0.498364051982143 0.959743958516081 0.340385726666133];
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'fitCsTp' );
% h = plot( fitresult, xData, yData );
% legend( h, 'CsTp vs. EpVec with errCsTp', 'fitCsTp', 'Location', 'NorthEast' );
% % Label axes
% xlabel EpVec
% ylabel CsTp
% grid on
